/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.edu.ecust.domain.entity.AutoScaler;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 */
@ApiModel(description = "Volume represents a named volume in a pod that may be accessed by any container in the pod.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-25T06:46:52.786Z[Etc/UTC]")
public class DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes {
  public static final String SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE = "awsElasticBlockStore";
  @SerializedName(SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAwsElasticBlockStore awsElasticBlockStore;

  public static final String SERIALIZED_NAME_AZURE_DISK = "azureDisk";
  @SerializedName(SERIALIZED_NAME_AZURE_DISK)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureDisk azureDisk;

  public static final String SERIALIZED_NAME_AZURE_FILE = "azureFile";
  @SerializedName(SERIALIZED_NAME_AZURE_FILE)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureFile azureFile;

  public static final String SERIALIZED_NAME_CEPHFS = "cephfs";
  @SerializedName(SERIALIZED_NAME_CEPHFS)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCephfs cephfs;

  public static final String SERIALIZED_NAME_CINDER = "cinder";
  @SerializedName(SERIALIZED_NAME_CINDER)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCinder cinder;

  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecConfigMap configMap;

  public static final String SERIALIZED_NAME_CSI = "csi";
  @SerializedName(SERIALIZED_NAME_CSI)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCsi csi;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_EMPTY_DIR = "emptyDir";
  @SerializedName(SERIALIZED_NAME_EMPTY_DIR)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecEmptyDir emptyDir;



  public static final String SERIALIZED_NAME_FC = "fc";
  @SerializedName(SERIALIZED_NAME_FC)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFc fc;

  public static final String SERIALIZED_NAME_FLEX_VOLUME = "flexVolume";
  @SerializedName(SERIALIZED_NAME_FLEX_VOLUME)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlexVolume flexVolume;

  public static final String SERIALIZED_NAME_FLOCKER = "flocker";
  @SerializedName(SERIALIZED_NAME_FLOCKER)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlocker flocker;

  public static final String SERIALIZED_NAME_GCE_PERSISTENT_DISK = "gcePersistentDisk";
  @SerializedName(SERIALIZED_NAME_GCE_PERSISTENT_DISK)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGcePersistentDisk gcePersistentDisk;

  public static final String SERIALIZED_NAME_GIT_REPO = "gitRepo";
  @SerializedName(SERIALIZED_NAME_GIT_REPO)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGitRepo gitRepo;

  public static final String SERIALIZED_NAME_GLUSTERFS = "glusterfs";
  @SerializedName(SERIALIZED_NAME_GLUSTERFS)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGlusterfs glusterfs;

  public static final String SERIALIZED_NAME_HOST_PATH = "hostPath";
  @SerializedName(SERIALIZED_NAME_HOST_PATH)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecHostPath hostPath;

  public static final String SERIALIZED_NAME_ISCSI = "iscsi";
  @SerializedName(SERIALIZED_NAME_ISCSI)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecIscsi iscsi;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NFS = "nfs";
  @SerializedName(SERIALIZED_NAME_NFS)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecNfs nfs;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPersistentVolumeClaim persistentVolumeClaim;

  public static final String SERIALIZED_NAME_PHOTON_PERSISTENT_DISK = "photonPersistentDisk";
  @SerializedName(SERIALIZED_NAME_PHOTON_PERSISTENT_DISK)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPhotonPersistentDisk photonPersistentDisk;

  public static final String SERIALIZED_NAME_PORTWORX_VOLUME = "portworxVolume";
  @SerializedName(SERIALIZED_NAME_PORTWORX_VOLUME)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPortworxVolume portworxVolume;

  public static final String SERIALIZED_NAME_PROJECTED = "projected";
  @SerializedName(SERIALIZED_NAME_PROJECTED)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjected projected;

  public static final String SERIALIZED_NAME_QUOBYTE = "quobyte";
  @SerializedName(SERIALIZED_NAME_QUOBYTE)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecQuobyte quobyte;

  public static final String SERIALIZED_NAME_RBD = "rbd";
  @SerializedName(SERIALIZED_NAME_RBD)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecRbd rbd;

  public static final String SERIALIZED_NAME_SCALE_I_O = "scaleIO";
  @SerializedName(SERIALIZED_NAME_SCALE_I_O)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecScaleIO scaleIO;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecSecret secret;

  public static final String SERIALIZED_NAME_STORAGEOS = "storageos";
  @SerializedName(SERIALIZED_NAME_STORAGEOS)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecStorageos storageos;

  public static final String SERIALIZED_NAME_VSPHERE_VOLUME = "vsphereVolume";
  @SerializedName(SERIALIZED_NAME_VSPHERE_VOLUME)
  private DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVsphereVolume vsphereVolume;


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes awsElasticBlockStore(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAwsElasticBlockStore awsElasticBlockStore) {
    
    this.awsElasticBlockStore = awsElasticBlockStore;
    return this;
  }

   /**
   * Get awsElasticBlockStore
   * @return awsElasticBlockStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAwsElasticBlockStore getAwsElasticBlockStore() {
    return awsElasticBlockStore;
  }


  public void setAwsElasticBlockStore(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAwsElasticBlockStore awsElasticBlockStore) {
    this.awsElasticBlockStore = awsElasticBlockStore;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes azureDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureDisk azureDisk) {
    
    this.azureDisk = azureDisk;
    return this;
  }

   /**
   * Get azureDisk
   * @return azureDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureDisk getAzureDisk() {
    return azureDisk;
  }


  public void setAzureDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureDisk azureDisk) {
    this.azureDisk = azureDisk;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes azureFile(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureFile azureFile) {
    
    this.azureFile = azureFile;
    return this;
  }

   /**
   * Get azureFile
   * @return azureFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureFile getAzureFile() {
    return azureFile;
  }


  public void setAzureFile(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecAzureFile azureFile) {
    this.azureFile = azureFile;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes cephfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCephfs cephfs) {
    
    this.cephfs = cephfs;
    return this;
  }

   /**
   * Get cephfs
   * @return cephfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCephfs getCephfs() {
    return cephfs;
  }


  public void setCephfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCephfs cephfs) {
    this.cephfs = cephfs;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes cinder(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCinder cinder) {
    
    this.cinder = cinder;
    return this;
  }

   /**
   * Get cinder
   * @return cinder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCinder getCinder() {
    return cinder;
  }


  public void setCinder(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCinder cinder) {
    this.cinder = cinder;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes configMap(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecConfigMap configMap) {
    this.configMap = configMap;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes csi(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCsi csi) {
    
    this.csi = csi;
    return this;
  }

   /**
   * Get csi
   * @return csi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCsi getCsi() {
    return csi;
  }


  public void setCsi(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecCsi csi) {
    this.csi = csi;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes downwardAPI(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes emptyDir(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecEmptyDir emptyDir) {
    
    this.emptyDir = emptyDir;
    return this;
  }

   /**
   * Get emptyDir
   * @return emptyDir
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecEmptyDir getEmptyDir() {
    return emptyDir;
  }


  public void setEmptyDir(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecEmptyDir emptyDir) {
    this.emptyDir = emptyDir;
  }






  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes fc(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFc fc) {
    
    this.fc = fc;
    return this;
  }

   /**
   * Get fc
   * @return fc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFc getFc() {
    return fc;
  }


  public void setFc(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFc fc) {
    this.fc = fc;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes flexVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlexVolume flexVolume) {
    
    this.flexVolume = flexVolume;
    return this;
  }

   /**
   * Get flexVolume
   * @return flexVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlexVolume getFlexVolume() {
    return flexVolume;
  }


  public void setFlexVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlexVolume flexVolume) {
    this.flexVolume = flexVolume;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes flocker(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlocker flocker) {
    
    this.flocker = flocker;
    return this;
  }

   /**
   * Get flocker
   * @return flocker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlocker getFlocker() {
    return flocker;
  }


  public void setFlocker(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecFlocker flocker) {
    this.flocker = flocker;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes gcePersistentDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGcePersistentDisk gcePersistentDisk) {
    
    this.gcePersistentDisk = gcePersistentDisk;
    return this;
  }

   /**
   * Get gcePersistentDisk
   * @return gcePersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGcePersistentDisk getGcePersistentDisk() {
    return gcePersistentDisk;
  }


  public void setGcePersistentDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGcePersistentDisk gcePersistentDisk) {
    this.gcePersistentDisk = gcePersistentDisk;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes gitRepo(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGitRepo gitRepo) {
    
    this.gitRepo = gitRepo;
    return this;
  }

   /**
   * Get gitRepo
   * @return gitRepo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGitRepo getGitRepo() {
    return gitRepo;
  }


  public void setGitRepo(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGitRepo gitRepo) {
    this.gitRepo = gitRepo;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes glusterfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGlusterfs glusterfs) {
    
    this.glusterfs = glusterfs;
    return this;
  }

   /**
   * Get glusterfs
   * @return glusterfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGlusterfs getGlusterfs() {
    return glusterfs;
  }


  public void setGlusterfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecGlusterfs glusterfs) {
    this.glusterfs = glusterfs;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes hostPath(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecHostPath hostPath) {
    
    this.hostPath = hostPath;
    return this;
  }

   /**
   * Get hostPath
   * @return hostPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecHostPath getHostPath() {
    return hostPath;
  }


  public void setHostPath(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecHostPath hostPath) {
    this.hostPath = hostPath;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes iscsi(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecIscsi iscsi) {
    
    this.iscsi = iscsi;
    return this;
  }

   /**
   * Get iscsi
   * @return iscsi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecIscsi getIscsi() {
    return iscsi;
  }


  public void setIscsi(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecIscsi iscsi) {
    this.iscsi = iscsi;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume&#39;s name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes nfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecNfs nfs) {
    
    this.nfs = nfs;
    return this;
  }

   /**
   * Get nfs
   * @return nfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecNfs getNfs() {
    return nfs;
  }


  public void setNfs(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecNfs nfs) {
    this.nfs = nfs;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes persistentVolumeClaim(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPersistentVolumeClaim persistentVolumeClaim) {
    
    this.persistentVolumeClaim = persistentVolumeClaim;
    return this;
  }

   /**
   * Get persistentVolumeClaim
   * @return persistentVolumeClaim
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPersistentVolumeClaim getPersistentVolumeClaim() {
    return persistentVolumeClaim;
  }


  public void setPersistentVolumeClaim(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPersistentVolumeClaim persistentVolumeClaim) {
    this.persistentVolumeClaim = persistentVolumeClaim;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes photonPersistentDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPhotonPersistentDisk photonPersistentDisk) {
    
    this.photonPersistentDisk = photonPersistentDisk;
    return this;
  }

   /**
   * Get photonPersistentDisk
   * @return photonPersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPhotonPersistentDisk getPhotonPersistentDisk() {
    return photonPersistentDisk;
  }


  public void setPhotonPersistentDisk(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPhotonPersistentDisk photonPersistentDisk) {
    this.photonPersistentDisk = photonPersistentDisk;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes portworxVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPortworxVolume portworxVolume) {
    
    this.portworxVolume = portworxVolume;
    return this;
  }

   /**
   * Get portworxVolume
   * @return portworxVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPortworxVolume getPortworxVolume() {
    return portworxVolume;
  }


  public void setPortworxVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecPortworxVolume portworxVolume) {
    this.portworxVolume = portworxVolume;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes projected(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjected projected) {
    
    this.projected = projected;
    return this;
  }

   /**
   * Get projected
   * @return projected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjected getProjected() {
    return projected;
  }


  public void setProjected(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjected projected) {
    this.projected = projected;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes quobyte(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecQuobyte quobyte) {
    
    this.quobyte = quobyte;
    return this;
  }

   /**
   * Get quobyte
   * @return quobyte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecQuobyte getQuobyte() {
    return quobyte;
  }


  public void setQuobyte(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecQuobyte quobyte) {
    this.quobyte = quobyte;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes rbd(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecRbd rbd) {
    
    this.rbd = rbd;
    return this;
  }

   /**
   * Get rbd
   * @return rbd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecRbd getRbd() {
    return rbd;
  }


  public void setRbd(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecRbd rbd) {
    this.rbd = rbd;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes scaleIO(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecScaleIO scaleIO) {
    
    this.scaleIO = scaleIO;
    return this;
  }

   /**
   * Get scaleIO
   * @return scaleIO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecScaleIO getScaleIO() {
    return scaleIO;
  }


  public void setScaleIO(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecScaleIO scaleIO) {
    this.scaleIO = scaleIO;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes secret(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecSecret getSecret() {
    return secret;
  }


  public void setSecret(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecSecret secret) {
    this.secret = secret;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes storageos(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecStorageos storageos) {
    
    this.storageos = storageos;
    return this;
  }

   /**
   * Get storageos
   * @return storageos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecStorageos getStorageos() {
    return storageos;
  }


  public void setStorageos(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecStorageos storageos) {
    this.storageos = storageos;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes vsphereVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVsphereVolume vsphereVolume) {
    
    this.vsphereVolume = vsphereVolume;
    return this;
  }

   /**
   * Get vsphereVolume
   * @return vsphereVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVsphereVolume getVsphereVolume() {
    return vsphereVolume;
  }


  public void setVsphereVolume(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVsphereVolume vsphereVolume) {
    this.vsphereVolume = vsphereVolume;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecVolumes {\n");
    sb.append("    awsElasticBlockStore: ").append(toIndentedString(awsElasticBlockStore)).append("\n");
    sb.append("    azureDisk: ").append(toIndentedString(azureDisk)).append("\n");
    sb.append("    azureFile: ").append(toIndentedString(azureFile)).append("\n");
    sb.append("    cephfs: ").append(toIndentedString(cephfs)).append("\n");
    sb.append("    cinder: ").append(toIndentedString(cinder)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    csi: ").append(toIndentedString(csi)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    emptyDir: ").append(toIndentedString(emptyDir)).append("\n");
    sb.append("    fc: ").append(toIndentedString(fc)).append("\n");
    sb.append("    flexVolume: ").append(toIndentedString(flexVolume)).append("\n");
    sb.append("    flocker: ").append(toIndentedString(flocker)).append("\n");
    sb.append("    gcePersistentDisk: ").append(toIndentedString(gcePersistentDisk)).append("\n");
    sb.append("    gitRepo: ").append(toIndentedString(gitRepo)).append("\n");
    sb.append("    glusterfs: ").append(toIndentedString(glusterfs)).append("\n");
    sb.append("    hostPath: ").append(toIndentedString(hostPath)).append("\n");
    sb.append("    iscsi: ").append(toIndentedString(iscsi)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nfs: ").append(toIndentedString(nfs)).append("\n");
    sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
    sb.append("    photonPersistentDisk: ").append(toIndentedString(photonPersistentDisk)).append("\n");
    sb.append("    portworxVolume: ").append(toIndentedString(portworxVolume)).append("\n");
    sb.append("    projected: ").append(toIndentedString(projected)).append("\n");
    sb.append("    quobyte: ").append(toIndentedString(quobyte)).append("\n");
    sb.append("    rbd: ").append(toIndentedString(rbd)).append("\n");
    sb.append("    scaleIO: ").append(toIndentedString(scaleIO)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    storageos: ").append(toIndentedString(storageos)).append("\n");
    sb.append("    vsphereVolume: ").append(toIndentedString(vsphereVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

