/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.edu.ecust.domain.entity.AutoScaler;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * information about the downwardAPI data to project
 */
@ApiModel(description = "information about the downwardAPI data to project")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-25T06:46:52.786Z[Etc/UTC]")
public class DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjectedDownwardAPI {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems> items = null;


  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjectedDownwardAPI items(List<DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems> items) {
    
    this.items = items;
    return this;
  }

  public DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjectedDownwardAPI addItemsItem(DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Items is a list of DownwardAPIVolume file
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Items is a list of DownwardAPIVolume file")

  public List<DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems> getItems() {
    return items;
  }


  public void setItems(List<DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecDownwardAPIItems> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainGpugroupGpugroupV1AutoScalerSpecPodTemplateSpecProjectedDownwardAPI {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

