/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.20.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.edu.ecust.domain.entity.AutoScaler;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

/**
 * Backend defines the referenced service endpoint to which the traffic will be forwarded to.
 */
@ApiModel(description = "Backend defines the referenced service endpoint to which the traffic will be forwarded to.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-25T06:46:52.786Z[Etc/UTC]")
public class DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecHttpBackend {
  public static final String SERIALIZED_NAME_RESOURCE = "resource";
  @SerializedName(SERIALIZED_NAME_RESOURCE)
  private DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendResource resource;

  public static final String SERIALIZED_NAME_SERVICE = "service";
  @SerializedName(SERIALIZED_NAME_SERVICE)
  private DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendService service;


  public DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecHttpBackend resource(DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendResource resource) {
    
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendResource getResource() {
    return resource;
  }


  public void setResource(DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendResource resource) {
    this.resource = resource;
  }


  public DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecHttpBackend service(DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendService service) {
    
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendService getService() {
    return service;
  }


  public void setService(DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecDefaultBackendService service) {
    this.service = service;
  }


  @Override
  public boolean equals(Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainGpugroupGpugroupV1AutoScalerSpecIngressConfigSpecHttpBackend {\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

