spring:
  #  resources:
  #    static-locations: classpath:static/js/,classpath:static/css/,classpath:static/img/,classpath:static/
  #  mvc:
  #    view:
  #      prefix: views/
  #      suffix: .html
  #  application:
  #    name: experiments
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

server:
  port: 8787
#  servlet:
#    context-path: /experiments

rabbitmq:
  host: 47.103.2.253
  port: 5672
  password: admin
  username: admin
  virtual-host: test
  template:
    exchange: exchange_pushmsg
  listener:
    auto-startup: true



#线程池配置信息
thread:
  pool:
    #是否启用线程池
    open: true
    #核心线程数
    corePoolSize: 50
    #最大线程数，包括核心线程与非核心线程
    maximumPoolSize: 100
    #非核心线程的闲置超时时间，超过这个时间就会被回收（秒）
    keepAliveTime: 3
    #排队深度，到达最大深度前不会创建非核心线程
    threadQueueSize: 2000

word:
  to:
    html:
      path: /tmp/docker/doc/

k8s:
  config: classpath:k8s/config
#  token:
  sharePvcName: "ai-resource"
  #clientConfig:
  #  group: "gpugroup.gpugroup.domain"
  #  namespace: "test-scaler"
  #  version: "v1"
  #  plural: "autoscalers" # String | The custom resource's plural name. For TPRs this would be lowercase plural kind.
  #  pretty: "" # String | If 'true', then the output is pretty printed.
  #  allowWatchBookmarks: true # Boolean | allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.
  #  _continue: "" # String | The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
  #  fieldSelector: "" # String | A selector to restrict the list of returned objects by their fields. Defaults to everything.
  #  labelSelector: "" # String | A selector to restrict the list of returned objects by their labels. Defaults to everything.
  #  limit: 56 # Integer | limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
  #  resourceVersion: "" # String | When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
  #  resourceVersionMatch: "" # String | resourceVersionMatch determines how resourceVersion is applied to list calls. It is highly recommended that resourceVersionMatch be set for list calls where resourceVersion is set See https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions for details.  Defaults to unset
  #  timeoutSeconds: 56 # Integer | Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
  #  watch: false # Boolean | Watch for changes to the described resources and return them as a stream of add, update, and remove notifications.
#guacamole:
#  ssh:
#    color-scheme: white-black
#  rdp:
#    ignore-cert: true
#    enable-wallpaper: true
#    enable-font-smoothing: true
#    enable-full-window-drag: true
#    enable-audio-input: true
#    #console: true
#    #console-audio: true
#    #启用文件传输
#    enable-drive: true
#    drive-path: /opt/file/
#    create-drive-path: true
#  vnc:
#    autoretry: 3
#    clipboard-encoding: UTF-8
#
#
#  hostname: 172.18.120.26
#  port: 4822
